# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e0b03fee550f1a4c30440a43ace77dc6a9369682b2884afb58c701c0ddc2d50acd4182dd3ec87399e3da984638200258b2689216dda32dc53744d046e7ff882

test:
  secret_key_base: 499cecf584f61562ec5a88f7f782179bb2ebe375a8ce7924bfcd0488967a16cd88cabfbe8b9aeca7f0391713bb6dd5d027dc5a7ca221ce2c54de4eef2257beae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
